<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  
  <title>捕获异常的那些事 | CoffeeTao的技术生活</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="theme-color" content="#4f6b79">
  <meta name="msapplication-TileColor" content="#4f6b79"/>
  
  
  <meta name="description" content="记得曾经有轮面试，面试官问我当在catch(Exception e)方法里面return掉，finally里面的数据会执行吗？当时由于对try-catch-finally机制没有全面的了解，猜了一个答案，会执行，竟然答对了，汗颜！！！ 这里还是总结一下，异常捕获应该注意些什么。 
throw Exception与try catch的的区别在开发业务的过程中，特别对于前端来说，比较依赖后端的数据，">
<meta property="og:type" content="article">
<meta property="og:title" content="捕获异常的那些事">
<meta property="og:url" content="http://yoursite.com/2016/05/03/捕获异常的那些事/index.html">
<meta property="og:site_name" content="CoffeeTao的技术生活">
<meta property="og:description" content="记得曾经有轮面试，面试官问我当在catch(Exception e)方法里面return掉，finally里面的数据会执行吗？当时由于对try-catch-finally机制没有全面的了解，猜了一个答案，会执行，竟然答对了，汗颜！！！ 这里还是总结一下，异常捕获应该注意些什么。 
throw Exception与try catch的的区别在开发业务的过程中，特别对于前端来说，比较依赖后端的数据，">
<meta property="og:updated_time" content="2016-05-03T05:09:58.000Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="捕获异常的那些事">
<meta name="twitter:description" content="记得曾经有轮面试，面试官问我当在catch(Exception e)方法里面return掉，finally里面的数据会执行吗？当时由于对try-catch-finally机制没有全面的了解，猜了一个答案，会执行，竟然答对了，汗颜！！！ 这里还是总结一下，异常捕获应该注意些什么。 
throw Exception与try catch的的区别在开发业务的过程中，特别对于前端来说，比较依赖后端的数据，">
  
  
    <link rel="icon" href="http://weibo.com/favicon.ico">
  
  
    <link rel="stylesheet" href="/css/style.css" type="text/css"> 
  

</head>

<body>
  <div id="container" class="container">
    <div class="left-col">
    <div class="intrude-less">
	<header id="header" class="inner">
		<a href="/" class="profilepic">
			
			<img src="http://upload.cccnews.com.cn/2014/0313/1394690263626.jpg" class="js-avatar" style="width: 100%;height: 100%;opacity: 1;">
			
		</a>
		
		<p class="header-subtitle">学着开心的编程...</p>
		
        <nav class="header-menu">
            <ul>
                
                    <li><a href="/archives">所有文章</a></li>
                
                    <li><a href="/tags/随笔/">随笔</a></li>
                
            </ul>
        </nav>
	</header>				
</div>


    </div>
    <div class="mid-col">
      <nav id="mobile-nav">
	<div class="intrude-less">
		<header id="header" class="inner">
			<a href="/" class="profilepic">
                
			        <img src="http://upload.cccnews.com.cn/2014/0313/1394690263626.jpg" class="js-avatar" style="width: 100%;height: 100%;opacity: 1;">
			    
			</a>
			<!-- <hgroup>
			  <h1 class="header-author">CoffeeTao</h1>
			</hgroup>-->
			
			<p class="header-subtitle">学着开心的编程...</p>
			
			<nav class="header-menu">
				<ul>
				
					<li><a href="/archives">所有文章</a></li>
		        
					<li><a href="/tags/随笔/">随笔</a></li>
		        
		        <div class="clearfix"></div>
				</ul>
			</nav>
		</header>				
	</div>
</nav>

      <div class="body-wrap"><article id="post-捕获异常的那些事" class="article article-type-post" itemscope itemprop="blogPost">
  
    <div class="article-meta">
      <a href="/2016/05/03/捕获异常的那些事/" class="article-date">
<span class="datetime-published-tag"> 2016-05-03 </span>
</a>

    </div>
  
  <div class="article-inner">
    
    
      <header class="article-header">
        
  
    <h1 class="article-title" itemprop="name">
      捕获异常的那些事
    </h1>
  

      </header>
      
      <div class="article-info article-info-post">
        <!-- 
 -->
        
	<div class="article-tag tagcloud">
		<ul class="article-tag-list"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/android/">android</a></li><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/java/">java</a></li></ul>
	</div>

        <div class="clearfix"></div>
      </div>
      
    
    <div class="article-entry" itemprop="articleBody">
      
        <p><strong> 记得曾经有轮面试，面试官问我当在catch(Exception e)方法里面return掉，finally里面的数据会执行吗？当时由于对try-catch-finally机制没有全面的了解，猜了一个答案，会执行，竟然答对了，汗颜！！！ 这里还是总结一下，异常捕获应该注意些什么。 </strong></p>
<h3 id="throw-Exception与try-catch的的区别"><a href="#throw-Exception与try-catch的的区别" class="headerlink" title="throw Exception与try catch的的区别"></a>throw Exception与try catch的的区别</h3><p>在开发业务的过程中，特别对于前端来说，比较依赖后端的数据，但是我们并不能完全信任后端的数据，这里我们往往会对后端的关键数据做异常处理，这里可能会有些同学偷懒直接throw Exception我们看看，直接throw Exception能否解决问题：</p>
<h3 id="throw-Exception"><a href="#throw-Exception" class="headerlink" title="throw Exception"></a>throw Exception</h3><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">/**</span><br><span class="line"> * Created by hongentao on 16/4/30.</span><br><span class="line"> */</span></span><br><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">TestDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        test();</span><br><span class="line">        System.out.println(<span class="string">"test"</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">test</span><span class="params">()</span> <span class="keyword">throws</span> NullPointerException </span>&#123;</span><br><span class="line">        String a = <span class="keyword">null</span>;</span><br><span class="line">        a.isEmpty();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>运行结果：<br>Exception in thread “main” java.lang.NullPointerException<br>    at TestDemo.test(TestDemo.java:12)<br>    at TestDemo.main(TestDemo.java:6)<br>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br>    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>    at java.lang.reflect.Method.invoke(Method.java:606)<br>    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)</p>
<p>Process finished with exit code 1</p>
<p>程序直接crash,空指针异常， exit code == 1异常退出，且”test”没有打印出来。</p>
<h3 id="try-catch"><a href="#try-catch" class="headerlink" title="try catch"></a>try catch</h3><p>try catch进行捕获看看结果又会是怎样的呢？</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">TestDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        test();</span><br><span class="line">        System.out.println(<span class="string">"test"</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">test</span><span class="params">()</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            String a = <span class="keyword">null</span>;</span><br><span class="line">            a.isEmpty();</span><br><span class="line">        &#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">            e.printStackTrace();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>运行结果：<br>test<br>java.lang.NullPointerException<br>    at TestDemo.test(TestDemo.java:16)<br>    at TestDemo.main(TestDemo.java:9)<br>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br>    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>    at java.lang.reflect.Method.invoke(Method.java:606)<br>    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)</p>
<p>Process finished with exit code 0</p>
<p>成功捕获异常， exit code == 0 正常退出，且“test”得到执行。</p>
<p><strong> 综上所述throw Exception并不能捕获异常仅仅是抛出了异常， 而try catch是可以捕获异常并且不会导致进程crash </strong></p>
<h3 id="finally关键字"><a href="#finally关键字" class="headerlink" title="finally关键字"></a>finally关键字</h3><p>finally关键字一定会执行，且跟try catch配合使用。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">TestDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        test();</span><br><span class="line">        System.out.println(<span class="string">"test"</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">test</span><span class="params">()</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            String a = <span class="keyword">null</span>;</span><br><span class="line">            a.isEmpty();</span><br><span class="line">        &#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">            e.printStackTrace();</span><br><span class="line">        &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">            System.out.println(<span class="string">"finally"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>运行结果：<br>java.lang.NullPointerException<br>finally<br>    at TestDemo.test(TestDemo.java:16)<br>test<br>    at TestDemo.main(TestDemo.java:9)<br>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br>    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>    at java.lang.reflect.Method.invoke(Method.java:606)<br>    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)</p>
<p>Process finished with exit code 0</p>
<p>finally被执行，正常退出；</p>
<p>这里回到文章开头的面试题，catch里面直接return看看finally是否得到执行：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">TestDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        test();</span><br><span class="line">        System.out.println(<span class="string">"test"</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">test</span><span class="params">()</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            String a = <span class="keyword">null</span>;</span><br><span class="line">            a.isEmpty();</span><br><span class="line">        &#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">            e.printStackTrace();</span><br><span class="line">            <span class="keyword">return</span>;</span><br><span class="line">        &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">            System.out.println(<span class="string">"finally"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br></pre></td></tr></table></figure></p>
<p>运行结果：<br>java.lang.NullPointerException<br>    at TestDemo.test(TestDemo.java:16)<br>    at TestDemo.main(TestDemo.java:9)<br>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br>    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>    at java.lang.reflect.Method.invoke(Method.java:606)<br>    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)<br>finally<br>test</p>
<p>Process finished with exit code 0</p>
<p>finally照样执行。</p>
<p><strong> 好了分析完毕。 </strong></p>

      
      
        <div class="post-copyright">
<p><a href="http://yoursite.com/2016/05/03/捕获异常的那些事/">本文</a>为原创，转载请遵守本站的版本</p>
<p class="updated-time" >更新于: </span>2016年5月3日 13:05</p>
</div>

      
    </div>
    
  </div>
  
    
<nav id="article-nav">
  
    <a href="/2016/05/12/gitignore注意事项/" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">&lt;</strong>
      <div class="article-nav-title">
        
          gitignore注意事项
        
      </div>
    </a>
  
  
    <a href="/2016/04/29/睿睿妈妈要开Blog了/" id="article-nav-older" class="article-nav-link-wrap">
      <div class="article-nav-title">睿睿妈妈要开Blog了</div>
      <strong class="article-nav-caption">&gt;</strong>
    </a>
  
</nav>


  
</article>





</div>
      <footer id="footer">
  <div class="outer">
    <div id="footer-info">
    	<div class="footer-left">
    		&copy; 2016
            
                 CoffeeTao
            
    	</div>
    </div>
  </div>
</footer>

    </div>
    <script>
	var ThemeXConfig = {
		fancybox: false,
		mathjax: false,
		animate: false,
		isHome: false,
		isPost: true,
		isArchive: false,
		isTag: false,
		isCategory: false,
		open_in_new: false,
     CDN_PATH: '' 
	}
</script>




    <script src="/js/jquery-1.9.1.min.js"></script>
    <script src="/js/common.js"></script>
    <script src="/js/jquery.lazyload.min.js"></script>







  </div>
</body>
</html>
